### ISSUE TITLE
Switching from requirejs/i18n to require-i18next

### ISSUE THREAD

**Issue by crebuh** [jcbvm/require-i18next#16]
Hi guys,

it seems require-i18next is the plugin I've searched for. Because with the default i18n plugin offered by require.js I've got a lot of problems when running the r.js optimizer.

I've seen that with the i18next plugin, you always have to call a method to get the values into your module/template etc. Due to the fact, that our project has grown and is very big there is a lot of rework to do. Is there a possibility to require the translations-files in the way, we already do it?

For example instead of:

       require(["some/module", "i18n!path/to/locales"], function(module, i18n) {
	    console.log(i18n.t("some_key"));

use this kind of access to the translation files

	require(["some/module", "i18n!path/to/locales"], function(module, locales) {
	    console.log(locales.some_key);

In addition I'm also wondering, hove to pass the locals to our underscore templates. For example at the moment we do the following. define a backbone view, and pass the labels to the template

    define([
        // labels
        'requirejs-i18n!nls/labels',
        // View Templates
        'text!templates/users/register/layout.html'
    ], function(
        Labels,
        // View Templates
        Template
    ) {
        'use strict';
        return Sportly.LayoutView.extend({
            template: function() {
                return _.template(Template, {
                    labels: Labels
                }, {
                    variable: 'data'
                });
            }
        });
    });

and use them in the template like this

    <h4 class="text-margin text-white text-big"><i class="fa fa-lock"></i>
        <%= data.labels.regions.modals.register.heading %>
    </h4>

thanks in advance. If there is a possible to achieve this, it would be awesome.

**Comment by jcbvm** [comment]
There is currently no possibility to return the translations instead of the i18next instance.

For your second question, I don't think i18next has a method to get all translations which you can pass to your templates, but instead you can pass the i18next instance to your template and call the translate function for getting a translation:

    _.template(Template, {
        t: i18n.t
    });

    <h4 class="text-margin text-white text-big"><i class="fa fa-lock"></i>
        <%= t('regions.modals.register.heading') %>
    </h4>

**Comment by crebuh** [comment]
Hi,

thanks for your fast response. The first problem is not a great hack, there a not a lot of translation directly in the code. So i think we can handle this.

For the second problem your solution is perfect! In comparison what do you think about this solution here: http://stackoverflow.com/questions/17676278/i18next-brunch-and-backbone-setup/17678413#17678413

Is it better/faster to work with data-i18n attributes in the template or passing the i18n.t-function to the templates, as you suggested?

And to be sure that also the optimization part works. Translations can be inlined into the build, so that the user can decided with translations to use? For example after changing to german, he page is reload (or maybe this is not needed here) the correct translations were used?

**Comment by jcbvm** [comment]
Personally I find the method passing nicer, but I don't think it should really matter performance wise, so it's up to you. 

If you inline the translations, all translations will be in your final file, so switch to a different supported language will to trigger any ajax call to get translation files. Downside is that your final file will be bigger. So it's up to you what you want.

Switching language should be possible without page reload (it is a while ago I looked into this, so I'm not really sure). It can be done by calling the following function on the i18next instance:

    i18n.setLng(<some language>, i18n.options, callback);

The callback argument is just an optional function which get called ones it's done setting the new language. Please note that passing the `i18n.options` is critical, because it contains the existing translations.

**Comment by crebuh** [comment]
@jcbvm 

We are currently in the middle of the migration process. After some changes the following error occurred. The console tells:

      Uncaught Error: Script error for: bower_components/require-i18next/require-i18next/i18next
	http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
	require.js:1924 GET http://localhost:8888/app/scripts/modules/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptLoad @ require.js:1699
	require.js:165 Uncaught Error: Script error for: module/bower_components/require-i18next/require-i18next/i18next
	http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
	require.js:1924 GET http://localhost:8888/app/scripts/views/layout/offers/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptLoad @ require.js:1699
	require.js:165 Uncaught Error: Script error for: view/layout/offers/bower_components/require-i18next/require-i18next/i18next
	http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
	require.js:1924 GET http://localhost:8888/app/scripts/views/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptLoad @ require.js:1699
	require.js:165 Uncaught Error: Script error for: view/bower_components/require-i18next/require-i18next/i18next
	http://requirejs.org/docs/errors.html#scripterror

What is interesting here is that the path, changes. Also the network tab shows, that the applications tries to load the require-next plugin several times. I am not sure why this happens? For example in nearly each view we have in the application we define the modules for it like this:

     define(['underscore','jquery','backbone','i18n!nls',function(_, $, Backbone, i18n)

Not sure if this forces require.js to load the plugin several times?

**Comment by jcbvm** [comment]
How does your requirejs looks like? Looks to me like it is failing to load the plugin from the bower components dir.




On Mon, Oct 12, 2015 at 5:37 AM -0700, "Christofer Huber" <notifications@github.com> wrote:
@jcbvm

We are currently in the middle of the migration process. After some changes the following error occurred. The console tells:

      Uncaught Error: Script error for: bower_components/require-i18next/require-i18next/i18next
        http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
        require.js:1924 GET http://localhost:8888/app/scripts/modules/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptLoad @ requir
 e.js:169
 9
        require.js:165 Uncaught Error: Script error for: module/bower_components/require-i18next/require-i18next/i18next
        http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
        require.js:1924 GET http://localhost:8888/app/scripts/views/layout/offers/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptL
 oad @ re
 quire.js:1699
        require.js:165 Uncaught Error: Script error for: view/layout/offers/bower_components/require-i18next/require-i18next/i18next
        http://requirejs.org/docs/errors.html#scripterrormakeError @ require.js:165context.onScriptError @ require.js:1709
        require.js:1924 GET http://localhost:8888/app/scripts/views/bower_components/require-i18next/require-i18next/i18next.js req.load @ require.js:1924context.load @ require.js:1667Module.load @ require.js:829Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165context.enable @ require.js:1538Module.callPlugin @ require.js:1087Module.fetch @ require.js:819Module.check @ require.js:851Module.enable @ require.js:1165(anonymous function) @ require.js:988(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929(anonymous function) @ require.js:1128(anonymous function) @ require.js:131(anonymous function) @ require.js:1178each @ require.js:56Module.emit @ require.js:1177Module.check @ require.js:929Module.enable @ require.js:1165Module.init @ require.js:783callGetModule @ require.js:1192context.completeLoad @ require.js:1571context.onScriptLoad @ require.
 js:1699
        require.js:165 Uncaught Error: Script error for: view/bower_components/require-i18next/require-i18next/i18next
        http://requirejs.org/docs/errors.html#scripterror

What is interesting here is that the path, changes. Also the network tab shows, that the applications tries to load the require-next plugin several times. I am not sure why this happens? For example in nearly each view we have in the application we define the modules for it like this:

     define(['underscore','jquery','backbone','i18n!nls',function(_, $, Backbone, i18n)

Not sure if this forces require.js to load the plugin several times?

---

**Comment by crebuh** [comment]
@jcbvm 

ok after some hours of research I found a solution now. I added a kind of wrapper module which returns only one instance of the i18n lib. so at the moment I am not using your plugin, but now I am not sure how to do the build. 

Here is the wrapper module: 

    define(['i18n-lib'], function(i18n) {
		'use strict';
		i18n.init({
			ns: 'labels',
			fallbackLng: 'en',
			// detectLngQS: 'locale',
			lowerCaseLng: true,
			useCookie: false,
			// supportedLngs: {
			// 	en: ['labels'],
			// 	de: ['labels']
			// },
			resGetPath: 'app/scripts/locales/__lng__/__ns__.json'
		});
		return i18n;
	}); 

here is the current config.js

     paths: {
        'i18n-lib': '../../bower_components/i18next/i18next.amd.withJQuery',
        'i18n': 'helper/general/i18n'
    },
    // map: {
    //     '*': {
    //         'i18n-lib': '../../bower_components/require-i18next/require-i18next/i18next'
    //     }
    // },

I had to outcomment the map attribute, otherwise I will get the following error:

        GET http://localhost:8888/app/scripts/i18next.js req.load 
	require.js:165 Uncaught Error: Script error for: i18next
	http://requirejs.org/docs/errors.html#scripterror

Is there a possibility to build without your plugin as well or do I need the plugin for the building process to inline the translation files?

**Comment by jcbvm** [comment]
There are a few things going wrong here. 

First of all you have a conflict with your `paths` and `map` config, `i18n-lib` here is pointing to two different files.

Second, you don't have to create a wrapper, the i18n plugin is already creating a single instance for you. The options for the init you defined in your wrapper can be passed via the requirejs config (the plugin is passing these options to i18next):

    requirejs.config({
        i18next: {
            supportedLngs: {
                en: ["namespace1", "namespace2"],
                nl: ["namespace1"]
            }
        }
    });

Third, the plugin has a dependency on `i18next`, this dependency should be declared in the paths section of your requirejs config:

    requirejs.config({
        map: {
            "*": {
                i18n: "../../bower_components/require-i18next/require-i18next/i18next"
            }
        },
        paths: {
            i18next: "../../bower_components/i18next/i18next.amd.withJQuery"
        }
    });

Hope this will help you to setup your config.

**Comment by jcbvm** [comment]
Inlining is possible if you still use i18n! References to load the locales.




On Mon, Oct 12, 2015 at 10:18 AM -0700, "Christofer Huber" <notifications@github.com> wrote:
@jcbvm

ok after some hours of research I found a solution now. I added a kind of wrapper module which returns only one instance of the i18n lib. so at the moment I am not using your plugin, but now I am not sure how to do the build.

Here is the wrapper module:

    define(['i18n-lib'], function(i18n) {
                'use strict';
                i18n.init({
                        ns: 'labels',
                        fallbackLng: 'en',
                        // detectLngQS: 'locale',
                        lowerCaseLng: true,
                        useCookie: false,
                        // supportedLngs: {
                        //      en: ['labels'],
                        //      de: ['labels']
                        // },
                        resGetPath: 'app/scripts/locales/__lng__/__ns__.json'
                });
                return i18n;
        });

here is the current config.js

     paths: {
        'i18n-lib': '../../bower_components/i18next/i18next.amd.withJQuery',
        'i18n': 'helper/general/i18n'
    },
    // map: {
    //     '*': {
    //         'i18n-lib': '../../bower_components/require-i18next/require-i18next/i18next'
    //     }
    // },

I had to outcomment the map attribute, otherwise I will get the following error:

        GET http://localhost:8888/app/scripts/i18next.js req.load
        require.js:165 Uncaught Error: Script error for: i18next
        http://requirejs.org/docs/errors.html#scripterror

Is there a possibility to build without your plugin as well or do I need the plugin for the building process to inline the translation files?

---

**Comment by jcbvm** [comment]
The inlining of locales depend on `i18n!someLocales` references and on the `supportedLngs` option this plugin adds to i18next config. 

So if you plan to run without this plugin you have to inline your locales yourself.

**Comment by crebuh** [comment]
@jcbvm 

that is the problem, if I use the suggest requirejs.config and change the dependencies to i18n!path/to/locales, it seems that there are several i18n-libs generated at once. Please have a look at the following screenshot ... not sure what the problem is.

http://pasteboard.co/1lBar77u.png

**Comment by jcbvm** [comment]
I'm also not sure, looks like it's running into a dependency loop

**Comment by jcbvm** [comment]
What version of i18next are you using?

**Comment by crebuh** [comment]
I upgraded now to 

i18next : v1.10.2
RequireJS i18next: v0.6.0

without success. Maybe I the dependencies a defined in a wrong way. As mentioned I modules looking like this:

      define([
            'underscore',
            'i18n!locales',
            'text!templates/trainers/offers/list/dropdown.html'
        ],
        function(_, i18n, Template) {
            console.log(i18n.t('general.search'));
        });

And the locales folder looks like this:

app/scripts/locales/
      - de.json
      - en.json

Due to the config for the paths

      resGetPath: 'app/scripts/locales/__lng__.json'

this should be ok I guess?

**Comment by jcbvm** [comment]
One thing I'm noticing here is that the resGetPath goes wrong I guess, the part after `i18n!` should be your resource location. The `restGetPath` config is only for the naming conventions (for resolving language and namespace within the name). 

With the above it would try to load locales from `locales/app/scripts/locales`, which is not what you want I guess.

But this seems unrelated to the mentioned problem.

**Comment by crebuh** [comment]
@jcbvm 

after turning on the debug mode, the console tells me that the translations were loaded correctly:

     currentLng set to: de-de
	i18next.amd.js:793 Does not exist: ./app/scripts/translations/locales/de-de/translation.json
	i18next.amd.js:793 loaded: ./app/scripts/translations/locales/de/translation.json
	i18next.amd.js:793 loaded: ./app/scripts/translations/locales/en/translation.json

But the dependency loop is still there.

**Comment by crebuh** [comment]
@jcbvm 

do you also know, how to include the .json-files to the build without using your plugin?

**Comment by jcbvm** [comment]
You can write a script to include the Jain files or maybe use require text for it. In your build you can pass I18next the resStore config option with your translations. It will not try to load any locales when you pass that option




On Tue, Oct 13, 2015 at 9:42 AM -0700, "Christofer Huber" <notifications@github.com> wrote:
@jcbvm

do you also know, how to include the .json-files to the build without using your plugin?

---
