### ISSUE TITLE
g.toUrl is not a function when i tried to load i18next.min file with requirejs  

### ISSUE THREAD

**Issue by shubh93** [jcbvm/require-i18next#18]
i also change the library version but still i am facing same problem when i try to load i18next.min file with requirejs. please give me some valuable suggestion to solve this problem.

**Comment by jcbvm** [comment]
What version of requirejs are you using? Can you share your project setup (requirejs config with i18next config)

**Comment by shubh93** [comment]
@jcbvm i am using 0.4.4 version of requirejs.  "grunt-contrib-requirejs": "^0.4.4",

require.config is with i18next
   paths:
    'jquery':                       '../libs/jquery/dist/jquery.min'
    'jquery-ui':                    '../libs/jquery-ui/jquery-ui.min'
    'jquery-ui-touch-punch' :       '../libs/jqueryui-touch-punch/jquery.ui.touch-punch.min'
    'jquery-form':                  '../libs/jquery-form/jquery.form'
    'jquery.xdomainrequest' :       '../libs/jquery-ajaxtransport-xdomainrequest/jquery.xdomainrequest.min'
    #'socket.io-client' :            '../libs/socket.io-client/socket.io'
    'gritter':                      '../libs/gritter/js/jquery.gritter.min'
    'backbone':                     '../libs/backbone/backbone'
    'underscore':                   '../libs/underscore/underscore-min'
    'ol':                           '../libs/ol3/build/ol'
    'ProtoBuf':                     '../libs/protobuf/dist/ProtoBuf.min'
    'ByteBuffer':                   '../libs/bytebuffer/dist/ByteBufferAB.min'
    'Long':                         '../libs/long/dist/long.min'
    'i18next':                      '../libs/i18next/i18next'
    'modernizr':                    '../libs/modernizr/modernizr'
    'jncf':                         '../libs/jnc'
    'routers':                      './common/routers'
    'views':                        './common/views'
    'controllers':                  './common/controllers'
    'factory':                      './common/factory'
    'models':                       './common/models'
    'utils':                        './utils'
    'templates':                    './templates'
    'menu':                         './modules/menu'
    'warnings':                     './modules/warnings'
    'tracks':                       './modules/tracks'
    'routes':                       './modules/routes'
    'settings':                     './modules/settings'
    'map_options':                  './modules/map_options'
    'login':                        './modules/login'
    'footer':                       './modules/footer'
    'catalog':                      './modules/catalog'
    'quickinfo':                    './modules/quick_info'
    'DictionaryHandler':            './utils/DictionaryHandler'
    'config':                       './config'


  map:
    '*':
      i18n: '../libs/require-i18next/require-i18next/i18next'


  shim:
    ol:
      exports: 'ol'
    modernizr:
      exports: 'Modernizr'
    gritter: ['jquery']

  i18next:
    ns           : 'messages'
    fallbackLng  : 'en'
    detectLngQS  : 'lang'
    lowerCaseLng : true
    useCookie    : false
    resGetPath   : '__ns__.__lng__.json'
    load         : 'unspecific'
    lngWhitelist : ['en', 'de', 'fr', 'it', 'es']


require ['jquery',
         'i18n!../locale',
         'jncf/jnc'
         'warnings/view/growl/site_warning'
], (($,  i18n ) ->

whenever i am trying to get in require 'i18n!..locale' i am facing g.tourl is not a function inside the i18next.

**Comment by shubh93** [comment]
@jcbvm now resolved the problem problem with my current require.config file BDW thank you so much for Replay :)
